version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 8080:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "user"
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - default_net
  redis:
    image: redis/redis-stack:7.2.0-v8
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
      - 8081:8001
    volumes:
      - ./redis/data/:/data/
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
      - REDISTIMESERIES_ARGS="RETENTION_POLICY=20"
    networks:
      - default_net
  minio:
    image: minio/minio:RELEASE.2024-03-07T00-43-48Z
    command: server /data --console-address ":9001"
    container_name: minio
    ports:
      - '9000:9000'
      - '8082:9001'
    networks:
      - default_net
    volumes:
      - ./minio/data/:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minioadmin
  minio-mc:
    container_name: minio-mc
    image: minio/mc:RELEASE.2024-03-07T00-31-49Z
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - minio
    networks:
      - default_net
    environment:
      - MC_HOST_myminio=http://admin:minioadmin@minio:9000
    entrypoint: /bin/bash
networks:
  default_net:
    driver: bridge
    name: rede-default    